#!/usr/bin/env bash
# ╔════════════════════════════════════════════════════════════════╗
# ║  MTProxy Installer (telemt + Fake TLS)                         ║
# ║                                                                ║
# ║  Architecture:                                                 ║
# ║    telemt on port 443 — MTProto proxy with TLS masking         ║
# ║    mask=true — non-MTProto traffic proxied to tls_domain       ║
# ║                                                                ║
# ║  Telegram → :443 → telemt (MTProto) → Telegram servers         ║
# ║  Browser  → :443 → telemt (not MTProto) → tls_domain site      ║
# ║                                                                ║
# ║  Based on: telemt (github.com/telemt/telemt)                   ║
# ╚════════════════════════════════════════════════════════════════╝
# VERSION=3.1.0

SCRIPT_VERSION="3.1.0"
APP_NAME="mtproxy"
SCRIPT_URL="https://raw.githubusercontent.com/ildar58/vpn_tools/main/caddy-mtproxy.sh"

set -euo pipefail

# ============================================
# Colors
# ============================================
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly WHITE='\033[1;37m'
readonly GRAY='\033[0;37m'
readonly NC='\033[0m'

# ============================================
# Configuration
# ============================================
INSTALL_DIR="/opt/mtproxy"
LOG_FILE="/var/log/mtproxy-installer.log"

TELEMT_CONTAINER="telemt"
TELEMT_IMAGE="ghcr.io/telemt/telemt:latest"
API_PORT="9091"

# ============================================
# Logging
# ============================================
log_info()    { echo -e "${WHITE}ℹ️  $*${NC}"; echo "[$(date '+%Y-%m-%d %H:%M:%S')] [INFO] $*" >> "$LOG_FILE" 2>/dev/null || true; }
log_success() { echo -e "${GREEN}✅ $*${NC}"; echo "[$(date '+%Y-%m-%d %H:%M:%S')] [OK] $*" >> "$LOG_FILE" 2>/dev/null || true; }
log_warning() { echo -e "${YELLOW}⚠️  $*${NC}"; echo "[$(date '+%Y-%m-%d %H:%M:%S')] [WARN] $*" >> "$LOG_FILE" 2>/dev/null || true; }
log_error()   { echo -e "${RED}❌ $*${NC}" >&2; echo "[$(date '+%Y-%m-%d %H:%M:%S')] [ERROR] $*" >> "$LOG_FILE" 2>/dev/null || true; }

# ============================================
# Helpers
# ============================================
check_root() {
    if [ "${EUID:-$(id -u)}" -ne 0 ]; then
        log_error "Скрипт должен быть запущен от root (sudo)"
        exit 1
    fi
}

get_server_ip() {
    local ip
    ip=$(curl -s -4 --connect-timeout 5 ifconfig.io 2>/dev/null) || \
    ip=$(curl -s -4 --connect-timeout 5 icanhazip.com 2>/dev/null) || \
    ip=$(curl -s -4 --connect-timeout 5 ipecho.net/plain 2>/dev/null) || \
    ip="127.0.0.1"
    echo "${ip:-127.0.0.1}"
}

check_port_available() {
    local port="$1"
    if ss -tlnp 2>/dev/null | grep -q ":${port} " || \
       netstat -tlnp 2>/dev/null | grep -q ":${port} "; then
        return 1
    fi
    return 0
}

command_exists() {
    command -v "$1" &>/dev/null
}

# ============================================
# Docker Installation
# ============================================
install_docker() {
    if command_exists docker; then
        log_success "Docker уже установлен: $(docker --version)"
        return 0
    fi

    log_info "Установка Docker..."
    curl -fsSL https://get.docker.com | bash
    systemctl enable docker
    systemctl start docker
    log_success "Docker установлен: $(docker --version)"
}

install_docker_compose() {
    if docker compose version &>/dev/null 2>&1; then
        log_success "Docker Compose уже установлен"
        return 0
    fi

    log_info "Установка Docker Compose plugin..."
    apt-get update -qq
    apt-get install -y -qq docker-compose-plugin 2>/dev/null || {
        local compose_url="https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)"
        curl -fsSL "$compose_url" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    }
    log_success "Docker Compose установлен"
}

# ============================================
# Secret Generation
# ============================================
generate_secret() {
    openssl rand -hex 16
}

# ============================================
# Config Generation
# ============================================
create_config_toml() {
    local tls_domain="$1"
    local secret="$2"
    local tag="${3:-}"
    local port="${4:-443}"

    local tag_line=""
    if [ -n "$tag" ]; then
        tag_line="ad_tag = \"$tag\""
    else
        tag_line="# ad_tag = \"\""
    fi

    cat > "$INSTALL_DIR/config.toml" << TOMLEOF
# ============================================
# telemt MTProxy Configuration
# Generated by $APP_NAME installer v$SCRIPT_VERSION
# ============================================

[general]
use_middle_proxy = true
log_level = "normal"
$tag_line

[general.modes]
classic = false
secure = false
tls = true

[general.links]
show = "*"

[server]
port = $port

[server.api]
enabled = true
listen = "0.0.0.0:$API_PORT"
whitelist = ["0.0.0.0/0"]

[[server.listeners]]
ip = "0.0.0.0"

[censorship]
tls_domain = "$tls_domain"
mask = true
tls_emulation = true
unknown_sni_action = "mask"

[access.users]
user = "$secret"
TOMLEOF

    log_success "config.toml создан"
}

create_docker_compose() {
    local port="${1:-443}"

    cat > "$INSTALL_DIR/docker-compose.yml" << DCEOF
services:
  telemt:
    image: ghcr.io/telemt/telemt:latest
    container_name: telemt
    restart: unless-stopped
    ports:
      - "${port}:443"
      - "127.0.0.1:9091:9091"
    working_dir: /run/telemt
    volumes:
      - ./config.toml:/run/telemt/config.toml:ro
    tmpfs:
      - /run/telemt:rw,mode=1777,size=1m
    environment:
      - RUST_LOG=info
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
DCEOF

    log_success "docker-compose.yml создан"
}

# ============================================
# Save/Load Configuration
# ============================================
save_config() {
    local domain="$1"
    local secret="$2"
    local server_ip="$3"
    local tag="${4:-}"
    local tls_domain="${5:-}"
    local port="${6:-443}"

    cat > "$INSTALL_DIR/.env" << EOF
DOMAIN=$domain
SECRET=$secret
SERVER_IP=$server_ip
TAG=$tag
TLS_DOMAIN=$tls_domain
PORT=$port
INSTALLED_AT=$(date '+%Y-%m-%d %H:%M:%S')
VERSION=$SCRIPT_VERSION
EOF
    chmod 600 "$INSTALL_DIR/.env"
}

load_config() {
    if [ -f "$INSTALL_DIR/.env" ]; then
        source "$INSTALL_DIR/.env"
        return 0
    fi
    return 1
}

# ============================================
# Firewall
# ============================================
setup_firewall() {
    local port="$1"

    if ! command_exists ufw; then
        log_info "UFW не найден, пропускаем настройку фаервола"
        return 0
    fi

    log_info "Открываем порт $port в UFW..."
    ufw allow "$port"/tcp comment "MTProxy telemt" 2>/dev/null || true
    log_success "Порт $port открыт в UFW"
}

# ============================================
# Link Generation
# ============================================
get_links_from_api() {
    local response
    response=$(curl -s --connect-timeout 3 "http://127.0.0.1:$API_PORT/v1/users" 2>/dev/null) || {
        return 1
    }
    echo "$response"
}

show_links() {
    if ! load_config; then
        log_error "Конфигурация не найдена. Сначала установите MTProxy."
        return 1
    fi

    local port="${PORT:-443}"
    local client_secret=""

    # Extract correct secret from API (telemt generates it properly)
    local api_response
    if api_response=$(get_links_from_api) && [ -n "$api_response" ] && [ "$api_response" != "null" ]; then
        if command_exists jq; then
            # Get first TLS link from API and extract the secret
            local api_link
            api_link=$(echo "$api_response" | jq -r '.data[0].links.tls[0] // empty' 2>/dev/null)
            if [ -n "$api_link" ]; then
                # Extract secret parameter from the tg:// link
                client_secret=$(echo "$api_link" | grep -oP 'secret=\K[0-9a-fA-F]+' 2>/dev/null || \
                                echo "$api_link" | sed -n 's/.*secret=\([0-9a-fA-F]*\).*/\1/p')
            fi
        fi
    fi

    # Fallback: build secret manually if API didn't return it
    if [ -z "$client_secret" ]; then
        local tls_hex
        tls_hex=$(echo -n "${TLS_DOMAIN}" | xxd -p | tr -d '\n')
        client_secret="ee${SECRET}${tls_hex}"
        log_warning "API недоступен, секрет сгенерирован вручную"
    fi

    echo ""
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    echo -e "${WHITE}  🔗 Ссылки для подключения к MTProxy${NC}"
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    echo ""

    if [ -n "${DOMAIN:-}" ] && [ "${DOMAIN}" != "${SERVER_IP:-}" ]; then
        echo -e "${GREEN}📌 По домену (рекомендуется):${NC}"
        echo ""
        echo -e "   ${WHITE}tg://proxy?server=${DOMAIN}&port=${port}&secret=${client_secret}${NC}"
        echo ""
        echo -e "   ${WHITE}https://t.me/proxy?server=${DOMAIN}&port=${port}&secret=${client_secret}${NC}"
        echo ""
    fi

    echo -e "${YELLOW}📌 По IP:${NC}"
    echo ""
    echo -e "   ${WHITE}tg://proxy?server=${SERVER_IP}&port=${port}&secret=${client_secret}${NC}"
    echo ""
    echo -e "   ${WHITE}https://t.me/proxy?server=${SERVER_IP}&port=${port}&secret=${client_secret}${NC}"
    echo ""
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
}

# ============================================
# Install Command
# ============================================
install_command() {
    check_root

    echo ""
    echo -e "${CYAN}╔════════════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║${NC}  ${WHITE}MTProxy Installer v${SCRIPT_VERSION}${NC}                        ${CYAN}║${NC}"
    echo -e "${CYAN}║${NC}  ${GRAY}telemt • Fake TLS • Docker${NC}                       ${CYAN}║${NC}"
    echo -e "${CYAN}╚════════════════════════════════════════════════════╝${NC}"
    echo ""

    # Check if already installed
    if [ -f "$INSTALL_DIR/.env" ]; then
        log_warning "MTProxy уже установлен в $INSTALL_DIR"
        read -p "Переустановить? (y/N): " reinstall
        if [[ ! "$reinstall" =~ ^[Yy]$ ]]; then
            log_info "Отмена"
            return 0
        fi
        cd "$INSTALL_DIR" && docker compose down 2>/dev/null || true
    fi

    # ── Step 1: Domain ──
    echo ""
    echo -e "${WHITE}─── Шаг 1: Домен сервера ───${NC}"
    echo -e "${GRAY}Домен, который указывает на этот сервер (для ссылок).${NC}"
    echo -e "${GRAY}Оставьте пустым, чтобы использовать только IP.${NC}"
    echo ""
    read -p "Домен (например, mt.example.com): " user_domain
    user_domain=$(echo "$user_domain" | xargs)

    # Get server IP
    local server_ip
    server_ip=$(get_server_ip)
    log_info "IP сервера: $server_ip"

    # Validate domain DNS if provided
    if [ -n "$user_domain" ]; then
        log_info "Проверяем DNS для $user_domain..."
        local dns_ip
        dns_ip=$(dig +short "$user_domain" A 2>/dev/null | head -1)
        if [ -n "$dns_ip" ]; then
            if [ "$dns_ip" = "$server_ip" ]; then
                log_success "DNS ✓ ($user_domain → $server_ip)"
            else
                log_warning "DNS указывает на $dns_ip, а IP сервера: $server_ip"
                read -p "Продолжить? (y/N): " cont
                [[ "$cont" =~ ^[Yy]$ ]] || { log_info "Отмена"; return 1; }
            fi
        else
            log_warning "Не удалось разрешить DNS для $user_domain"
            read -p "Продолжить? (y/N): " cont
            [[ "$cont" =~ ^[Yy]$ ]] || { log_info "Отмена"; return 1; }
        fi
    fi

    # ── Step 2: TLS Domain ──
    echo ""
    echo -e "${WHITE}─── Шаг 2: TLS домен для маскировки ───${NC}"
    echo -e "${GRAY}Домен, под который будет маскироваться трафик прокси.${NC}"
    echo -e "${GRAY}При обращении браузером на :443 будет показан этот сайт.${NC}"
    echo -e "${GRAY}Рекомендуется: крупный популярный сайт (google.com, microsoft.com и т.д.)${NC}"
    echo ""
    read -p "TLS домен [google.com]: " user_tls_domain
    user_tls_domain=$(echo "${user_tls_domain:-google.com}" | xargs)

    # ── Step 3: Port ──
    echo ""
    echo -e "${WHITE}─── Шаг 3: Порт ───${NC}"
    echo ""
    read -p "Порт MTProxy [443]: " user_port
    user_port="${user_port:-443}"

    if [ "$user_port" != "443" ] && ! check_port_available "$user_port"; then
        log_warning "Порт $user_port уже занят!"
        read -p "Продолжить? (y/N): " cont
        [[ "$cont" =~ ^[Yy]$ ]] || { log_info "Отмена"; return 1; }
    fi

    # ── Step 4: TAG ──
    echo ""
    echo -e "${WHITE}─── Шаг 4: Промо TAG (необязательно) ───${NC}"
    echo -e "${GRAY}Получите TAG у @MTProxybot в Telegram для продвижения канала.${NC}"
    echo -e "${GRAY}⚠️  Ссылка от бота НЕ будет работать — используйте только TAG.${NC}"
    echo -e "${GRAY}Можно добавить позже: $APP_NAME update-tag${NC}"
    echo ""
    read -p "Введите TAG (оставьте пустым для пропуска): " user_tag

    if [ -n "$user_tag" ]; then
        if [[ ! "$user_tag" =~ ^[0-9a-fA-F]{32}$ ]]; then
            log_warning "TAG должен быть 32-символьной HEX строкой. Пропускаем."
            user_tag=""
        fi
    fi

    # ── Step 5: Secret ──
    echo ""
    echo -e "${WHITE}─── Шаг 5: Секрет (необязательно) ───${NC}"
    echo -e "${GRAY}Можете ввести свой 32-символьный HEX секрет или оставить пустым${NC}"
    echo -e "${GRAY}для автоматической генерации.${NC}"
    echo ""
    read -p "Секрет (Enter = сгенерировать): " user_secret
    user_secret=$(echo "$user_secret" | xargs)

    local secret
    if [ -n "$user_secret" ]; then
        if [[ ! "$user_secret" =~ ^[0-9a-fA-F]{32}$ ]]; then
            log_error "Секрет должен быть ровно 32 HEX символа (0-9, a-f)"
            log_info "Генерируем случайный секрет..."
            secret=$(generate_secret)
        else
            secret="$user_secret"
            log_success "Используем указанный секрет"
        fi
    else
        secret=$(generate_secret)
        log_success "Секрет сгенерирован"
    fi

    # ── Summary ──
    echo ""
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    echo -e "${WHITE}  📋 Параметры установки:${NC}"
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    printf "   ${WHITE}%-20s${NC} ${GRAY}%s${NC}\n" "Домен:" "${user_domain:-не задан}"
    printf "   ${WHITE}%-20s${NC} ${GRAY}%s${NC}\n" "IP:" "$server_ip"
    printf "   ${WHITE}%-20s${NC} ${GRAY}%s${NC}\n" "TLS домен:" "$user_tls_domain"
    printf "   ${WHITE}%-20s${NC} ${GRAY}%s${NC}\n" "Порт:" "$user_port"
    printf "   ${WHITE}%-20s${NC} ${GRAY}%s${NC}\n" "Секрет:" "$secret"
    printf "   ${WHITE}%-20s${NC} ${GRAY}%s${NC}\n" "TAG:" "${user_tag:-не задан}"
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    echo ""

    read -p "Начать установку? (Y/n): " confirm
    if [[ "$confirm" =~ ^[Nn]$ ]]; then
        log_info "Отмена"
        return 0
    fi

    # ── Install dependencies ──
    log_info "Установка зависимостей..."
    apt-get update -qq
    apt-get install -y -qq curl jq dnsutils xxd openssl 2>/dev/null || true

    install_docker
    install_docker_compose

    # ── Create directory structure ──
    mkdir -p "$INSTALL_DIR"

    # ── Generate configs ──
    create_config_toml "$user_tls_domain" "$secret" "$user_tag" "$user_port"
    create_docker_compose "$user_port"
    save_config "$user_domain" "$secret" "$server_ip" "$user_tag" "$user_tls_domain" "$user_port"

    # ── Firewall ──
    setup_firewall "$user_port"

    # ── Pull and start ──
    log_info "Скачиваем образ telemt..."
    cd "$INSTALL_DIR"
    docker compose pull

    log_info "Запускаем MTProxy..."
    docker compose up -d

    # Wait for API
    log_info "Ждём запуска API..."
    local retries=0
    while [ $retries -lt 10 ]; do
        if curl -s --connect-timeout 1 "http://127.0.0.1:$API_PORT/v1/users" &>/dev/null; then
            break
        fi
        sleep 1
        retries=$((retries + 1))
    done

    # ── Install management command ──
    install_management_command

    # ── Done ──
    echo ""
    echo -e "${GREEN}╔════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║${NC}  ${WHITE}✅ MTProxy успешно установлен!${NC}                    ${GREEN}║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════════════════════╝${NC}"
    echo ""

    show_links

    echo ""
    echo -e "${WHITE}Управление:${NC}"
    echo -e "   ${CYAN}mtproxy${NC}          — интерактивное меню"
    echo -e "   ${CYAN}mtproxy status${NC}   — статус контейнера"
    echo -e "   ${CYAN}mtproxy links${NC}    — ссылки для подключения"
    echo -e "   ${CYAN}mtproxy help${NC}     — все команды"
    echo ""
}

# ============================================
# Management Command Installation
# ============================================
install_management_command() {
    local script_dest="$INSTALL_DIR/$APP_NAME.sh"
    local bin_link="/usr/local/bin/$APP_NAME"

    # Determine source: $0 may be /dev/stdin or a pipe when run via curl | bash
    local script_source
    script_source=$(readlink -f "$0" 2>/dev/null || echo "$0")

    if [ -f "$script_source" ] && [ "$script_source" != "/dev/stdin" ] && \
       [ "$script_source" != "/proc/self/fd/0" ] && [ "$script_source" != "-bash" ]; then
        # Script was run from a file — copy it
        cp "$script_source" "$script_dest"
    elif [ -f "$script_dest" ]; then
        # Already installed, keep existing
        log_info "Скрипт уже на месте: $script_dest"
    else
        # Piped via curl | bash — download the script
        log_info "Скачиваем скрипт в $script_dest..."
        if [ -n "${SCRIPT_URL:-}" ] && [ "$SCRIPT_URL" != "https://raw.githubusercontent.com/YOUR_USER/YOUR_REPO/main/caddy-mtproxy.sh" ]; then
            curl -fsSL "$SCRIPT_URL" -o "$script_dest"
        else
            # Fallback: re-read from stdin is not possible, embed self
            log_warning "Не удалось определить источник скрипта."
            log_warning "Скопируйте скрипт вручную в $script_dest"
            log_warning "Затем выполните: chmod +x $script_dest"
        fi
    fi

    chmod +x "$script_dest" 2>/dev/null || true

    # Create /usr/local/bin wrapper (always overwrite to fix broken installs)
    cat > "$bin_link" << 'BINEOF'
#!/usr/bin/env bash
exec bash "/opt/mtproxy/mtproxy.sh" "$@"
BINEOF

    chmod +x "$bin_link"

    # Verify installation
    if [ -x "$bin_link" ] && [ -f "$script_dest" ]; then
        log_success "Команда '$APP_NAME' установлена → $bin_link"
    else
        log_warning "Не удалось зарегистрировать команду. Запускайте вручную:"
        echo -e "   ${CYAN}bash $script_dest${NC}"
    fi
}

# ============================================
# Service Commands
# ============================================
up_command() {
    check_root
    if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_error "MTProxy не установлен. Запустите: $APP_NAME install"
        exit 1
    fi
    log_info "Запускаем MTProxy..."
    cd "$INSTALL_DIR" && docker compose up -d
    log_success "MTProxy запущен"
}

down_command() {
    check_root
    if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_error "MTProxy не установлен."
        exit 1
    fi
    log_info "Останавливаем MTProxy..."
    cd "$INSTALL_DIR" && docker compose down
    log_success "MTProxy остановлен"
}

restart_command() {
    check_root
    if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_error "MTProxy не установлен."
        exit 1
    fi
    log_info "Перезапускаем MTProxy..."
    cd "$INSTALL_DIR" && docker compose restart
    log_success "MTProxy перезапущен"
}

status_command() {
    if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_error "MTProxy не установлен."
        exit 1
    fi

    echo ""
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    echo -e "${WHITE}  📊 Статус MTProxy${NC}"
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
    echo ""

    local status
    status=$(docker inspect --format='{{.State.Status}}' "$TELEMT_CONTAINER" 2>/dev/null || echo "не найден")
    local uptime
    uptime=$(docker inspect --format='{{.State.StartedAt}}' "$TELEMT_CONTAINER" 2>/dev/null || echo "N/A")

    if [ "$status" = "running" ]; then
        echo -e "   ${GREEN}●${NC} Контейнер: ${GREEN}работает${NC}"
        echo -e "   ${WHITE}  Запущен: ${GRAY}$uptime${NC}"
    elif [ "$status" = "не найден" ]; then
        echo -e "   ${RED}●${NC} Контейнер: ${RED}не найден${NC}"
    else
        echo -e "   ${RED}●${NC} Контейнер: ${RED}$status${NC}"
    fi

    if load_config; then
        echo ""
        printf "   ${WHITE}%-15s${NC} ${GRAY}%s${NC}\n" "Домен:" "${DOMAIN:-не задан}"
        printf "   ${WHITE}%-15s${NC} ${GRAY}%s${NC}\n" "IP:" "${SERVER_IP:-N/A}"
        printf "   ${WHITE}%-15s${NC} ${GRAY}%s${NC}\n" "TLS домен:" "${TLS_DOMAIN:-N/A}"
        printf "   ${WHITE}%-15s${NC} ${GRAY}%s${NC}\n" "Порт:" "${PORT:-443}"

        if [ -n "${TAG:-}" ]; then
            printf "   ${WHITE}%-15s${NC} ${GRAY}%s${NC}\n" "TAG:" "$TAG"
        fi
    fi

    echo ""
    if curl -s --connect-timeout 2 "http://127.0.0.1:$API_PORT/v1/users" &>/dev/null; then
        echo -e "   ${GREEN}●${NC} API: ${GREEN}доступен${NC} (порт $API_PORT)"
    else
        echo -e "   ${YELLOW}●${NC} API: ${YELLOW}недоступен${NC}"
    fi

    echo ""
    echo -e "${CYAN}════════════════════════════════════════════════════${NC}"
}

links_command() {
    show_links
}

logs_command() {
    if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_error "MTProxy не установлен."
        exit 1
    fi
    echo -e "${GRAY}(Ctrl+C для выхода)${NC}"
    cd "$INSTALL_DIR" && docker compose logs -f --tail=50
}

# ============================================
# Update TAG
# ============================================
update_tag_command() {
    check_root

    if ! load_config; then
        log_error "Конфигурация не найдена."
        return 1
    fi

    echo ""
    echo -e "${WHITE}─── Обновление TAG ───${NC}"
    echo -e "${GRAY}Текущий TAG: ${TAG:-не задан}${NC}"
    echo -e "${GRAY}Получите TAG у @MTProxybot в Telegram${NC}"
    echo -e "${GRAY}⚠️  Ссылка от бота НЕ будет работать — используйте только TAG.${NC}"
    echo ""
    read -p "Введите TAG (пусто для удаления): " new_tag

    if [ -n "$new_tag" ]; then
        if [[ ! "$new_tag" =~ ^[0-9a-fA-F]{32}$ ]]; then
            log_error "TAG должен быть 32-символьной HEX строкой"
            return 1
        fi
    fi

    sed -i "s/^TAG=.*/TAG=$new_tag/" "$INSTALL_DIR/.env"
    create_config_toml "${TLS_DOMAIN}" "${SECRET}" "$new_tag" "${PORT:-443}"

    log_info "Перезапускаем MTProxy..."
    cd "$INSTALL_DIR" && docker compose restart

    if [ -n "$new_tag" ]; then
        log_success "TAG обновлён: $new_tag"
    else
        log_success "TAG удалён"
    fi
}

# ============================================
# Update TLS Domain
# ============================================
update_tls_domain_command() {
    check_root

    if ! load_config; then
        log_error "Конфигурация не найдена."
        return 1
    fi

    echo ""
    echo -e "${WHITE}─── Обновление TLS домена ───${NC}"
    echo -e "${GRAY}Текущий TLS домен: ${TLS_DOMAIN:-не задан}${NC}"
    echo -e "${RED}⚠️  Смена TLS домена сделает все текущие ссылки недействительными!${NC}"
    echo ""
    read -p "Новый TLS домен: " new_tls_domain

    if [ -z "$new_tls_domain" ]; then
        log_error "Домен не может быть пустым"
        return 1
    fi

    sed -i "s/^TLS_DOMAIN=.*/TLS_DOMAIN=$new_tls_domain/" "$INSTALL_DIR/.env"
    create_config_toml "$new_tls_domain" "${SECRET}" "${TAG:-}" "${PORT:-443}"

    log_info "Перезапускаем MTProxy..."
    cd "$INSTALL_DIR" && docker compose restart

    log_success "TLS домен обновлён: $new_tls_domain"
    echo ""
    log_warning "Все старые ссылки больше не работают! Получите новые:"
    echo -e "   ${CYAN}$APP_NAME links${NC}"
}

# ============================================
# Edit Configuration
# ============================================
edit_command() {
    check_root

    if [ ! -f "$INSTALL_DIR/config.toml" ]; then
        log_error "Конфигурация не найдена."
        return 1
    fi

    local editor="${EDITOR:-nano}"
    if ! command_exists "$editor"; then
        editor="vi"
    fi

    log_info "Открываем config.toml в $editor..."
    "$editor" "$INSTALL_DIR/config.toml"

    read -p "Перезапустить MTProxy для применения изменений? (Y/n): " restart_choice
    if [[ ! "$restart_choice" =~ ^[Nn]$ ]]; then
        cd "$INSTALL_DIR" && docker compose restart
        log_success "MTProxy перезапущен"
    fi
}

# ============================================
# Update (pull latest image)
# ============================================
update_command() {
    check_root

    if [ ! -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_error "MTProxy не установлен."
        exit 1
    fi

    log_info "Обновляем образ telemt..."
    cd "$INSTALL_DIR"
    docker compose pull

    log_info "Перезапускаем с новым образом..."
    docker compose up -d

    log_success "MTProxy обновлён до последней версии"
}

# ============================================
# Uninstall
# ============================================
uninstall_command() {
    check_root

    echo ""
    echo -e "${RED}╔════════════════════════════════════════════════════╗${NC}"
    echo -e "${RED}║${NC}  ${WHITE}⚠️  Удаление MTProxy${NC}                              ${RED}║${NC}"
    echo -e "${RED}╚════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}Будут удалены:${NC}"
    echo "   • Docker контейнер telemt"
    echo "   • Директория $INSTALL_DIR"
    echo "   • Команда /usr/local/bin/$APP_NAME"
    echo ""

    read -p "Вы уверены? (y/N): " confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        log_info "Отмена"
        return 0
    fi

    if [ -f "$INSTALL_DIR/docker-compose.yml" ]; then
        log_info "Останавливаем контейнеры..."
        cd "$INSTALL_DIR" && docker compose down -v 2>/dev/null || true
    fi

    docker rmi "$TELEMT_IMAGE" 2>/dev/null || true
    rm -rf "$INSTALL_DIR"
    rm -f /usr/local/bin/"$APP_NAME"

    if command_exists ufw; then
        ufw delete allow 443/tcp 2>/dev/null || true
    fi

    echo ""
    log_success "MTProxy полностью удалён"
}

# ============================================
# Help
# ============================================
show_help() {
    echo ""
    echo -e "${CYAN}MTProxy Manager v${SCRIPT_VERSION}${NC} (telemt)"
    echo ""
    echo -e "${WHITE}Использование:${NC} $APP_NAME [команда]"
    echo ""
    echo -e "${WHITE}Команды:${NC}"
    printf "   ${CYAN}%-18s${NC} %s\n" "install"       "📦 Установить MTProxy"
    printf "   ${CYAN}%-18s${NC} %s\n" "up / start"    "▶️  Запустить"
    printf "   ${CYAN}%-18s${NC} %s\n" "down / stop"   "⏹️  Остановить"
    printf "   ${CYAN}%-18s${NC} %s\n" "restart"       "🔄 Перезапустить"
    printf "   ${CYAN}%-18s${NC} %s\n" "status"        "📊 Статус"
    printf "   ${CYAN}%-18s${NC} %s\n" "links"         "🔗 Показать ссылки"
    printf "   ${CYAN}%-18s${NC} %s\n" "logs"          "📜 Логи (live)"
    printf "   ${CYAN}%-18s${NC} %s\n" "update-tag"    "🏷️  Обновить TAG"
    printf "   ${CYAN}%-18s${NC} %s\n" "update-tls"    "🌐 Сменить TLS домен"
    printf "   ${CYAN}%-18s${NC} %s\n" "update"        "⬆️  Обновить telemt"
    printf "   ${CYAN}%-18s${NC} %s\n" "edit"          "✏️  Редактировать config"
    printf "   ${CYAN}%-18s${NC} %s\n" "uninstall"     "🗑️  Удалить"
    printf "   ${CYAN}%-18s${NC} %s\n" "menu"          "📋 Интерактивное меню"
    printf "   ${CYAN}%-18s${NC} %s\n" "help"          "❓ Эта справка"
    echo ""
    echo -e "${GRAY}Без аргументов — интерактивное меню${NC}"
    echo ""
}

# ============================================
# Interactive Menu
# ============================================
main_menu() {
    while true; do
        clear
        echo ""
        echo -e "${CYAN}╔════════════════════════════════════════════════════╗${NC}"
        echo -e "${CYAN}║${NC}  ${WHITE}🚀 MTProxy Manager v${SCRIPT_VERSION}${NC}                       ${CYAN}║${NC}"
        echo -e "${CYAN}║${NC}  ${GRAY}telemt • Fake TLS • Docker${NC}                       ${CYAN}║${NC}"
        echo -e "${CYAN}╚════════════════════════════════════════════════════╝${NC}"
        echo ""

        local container_status
        container_status=$(docker inspect --format='{{.State.Status}}' "$TELEMT_CONTAINER" 2>/dev/null || echo "не установлен")
        if [ "$container_status" = "running" ]; then
            echo -e "   Статус: ${GREEN}● работает${NC}"
        else
            echo -e "   Статус: ${RED}● $container_status${NC}"
        fi
        echo ""

        echo -e "${WHITE}   Выберите действие:${NC}"
        echo ""
        echo -e "   ${CYAN} 1)${NC}  📦 Установить MTProxy"
        echo -e "   ${CYAN} 2)${NC}  ▶️  Запустить"
        echo -e "   ${CYAN} 3)${NC}  ⏹️  Остановить"
        echo -e "   ${CYAN} 4)${NC}  🔄 Перезапустить"
        echo -e "   ${CYAN} 5)${NC}  📊 Статус"
        echo -e "   ${CYAN} 6)${NC}  🔗 Ссылки"
        echo -e "   ${CYAN} 7)${NC}  📜 Логи"
        echo -e "   ${CYAN} 8)${NC}  🏷️  Обновить TAG"
        echo -e "   ${CYAN} 9)${NC}  🌐 Сменить TLS домен"
        echo -e "   ${CYAN}10)${NC}  ⬆️  Обновить telemt"
        echo -e "   ${CYAN}11)${NC}  ✏️  Редактировать config"
        echo -e "   ${CYAN}12)${NC}  🗑️  Удалить"
        echo -e "   ${CYAN} 0)${NC}  🚪 Выход"
        echo ""

        read -p "   Выбор [0-12]: " choice

        case "$choice" in
            1)  install_command; read -p "Нажмите Enter..." ;;
            2)  up_command; read -p "Нажмите Enter..." ;;
            3)  down_command; read -p "Нажмите Enter..." ;;
            4)  restart_command; read -p "Нажмите Enter..." ;;
            5)  status_command; read -p "Нажмите Enter..." ;;
            6)  links_command; read -p "Нажмите Enter..." ;;
            7)  logs_command ;;
            8)  update_tag_command; read -p "Нажмите Enter..." ;;
            9)  update_tls_domain_command; read -p "Нажмите Enter..." ;;
            10) update_command; read -p "Нажмите Enter..." ;;
            11) edit_command; read -p "Нажмите Enter..." ;;
            12) uninstall_command; read -p "Нажмите Enter..." ;;
            0)  echo ""; log_info "До свидания!"; exit 0 ;;
            *)  log_error "Неверный выбор"; sleep 1 ;;
        esac
    done
}

# ============================================
# MAIN ENTRY POINT
# ============================================
COMMAND="${1:-}"

case "$COMMAND" in
    install)        install_command ;;
    up|start)       up_command ;;
    down|stop)      down_command ;;
    restart)        restart_command ;;
    status)         status_command ;;
    logs)           logs_command ;;
    links)          links_command ;;
    update-tag)     update_tag_command ;;
    update-tls)     update_tls_domain_command ;;
    update)         update_command ;;
    edit)           edit_command ;;
    uninstall)      uninstall_command ;;
    help|-h|--help) show_help ;;
    menu)           main_menu ;;
    "")             main_menu ;;
    *)
        log_error "Неизвестная команда: $COMMAND"
        echo "Используйте: $APP_NAME help"
        exit 1
        ;;
esac
